# Generated by Django 5.2 on 2025-05-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientprofile_created_at_patientprofile_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='approve',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
