# Generated by Django 5.2 on 2025-07-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_doctorprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_nurse',
            field=models.BooleanField(default=False),
        ),
    ]
