# Generated by Django 5.2 on 2025-07-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_nurseprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
