# Generated by Django 5.2 on 2025-07-04 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_otpverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpverification',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
